name: Package

on:
  push:
  pull_request:
  repository_dispatch:
    type: [rebuild]
  workflow_dispatch:

jobs:
  build_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get build order
        id: set-build-order
        run: |
          echo "build_order=$(./get_depends.py)" >> $GITHUB_OUTPUT
          echo "container=$(echo ghcr.io/${{ github.repository_owner }}/nxdk|tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    outputs:
      build_order: ${{ steps.set-build-order.outputs.build_order }}
      container:  ${{ steps.set-build-order.outputs.container }}

  build:
    needs: [build_order]
    runs-on: ubuntu-latest
    container: ${{ needs.build_order.outputs.container }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.build_order.outputs.build_order) }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare pacman
        run: |
          cp .github/workflows/config/pacman.conf /etc/pacman.conf
          cp .github/workflows/config/makepkg.conf /etc/makepkg.conf
          mkdir -p /usr/src/nxdk/var/lib/pacman/  /usr/src/nxdk/var/cache/pacman/ /usr/src/nxdk/log /usr/src/nxdk/pacman.d/
      - name: Build package
        run: |
          eval $(/usr/src/nxdk/bin/activate -s)
          for f in ${{ matrix.package }}; do
          chown -R nobody:nobody $f
          cd $f
          sudo -u nobody NXDK_DIR=${NXDK_DIR} makepkg -p NXBUILD --cleanbuild --ignorearch --noconfirm
          pacman -U --noconfirm *.pkg.* --overwrite '*'
          cd ..
          done
      - name: Get package name
        run: |
          export PACKAGE=`echo ${{ matrix.package }} | awk '{print $NF}'`
          echo "PACKAGE=$PACKAGE" >> $GITHUB_ENV
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ env.PACKAGE }}
          path: ${{ env.PACKAGE }}/*.pkg.tar.gz
  
  create_release:
    if: contains(github.ref,'refs/heads/main')
    needs: [build_order, build]
    runs-on: ubuntu-latest
    container: ${{ needs.build_order.outputs.container }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Create repo files
      run: |
        mkdir packages
        cp package-*/*.pkg.tar.gz packages/
        cd packages
        repo-add nxdk.db.tar.gz *.pkg.tar.gz
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/*
        overwrite: true
        file_glob: true
        tag: ${{ github.ref }}-${{ github.run_id }}
        release_name: ${{ github.ref }} (${{ github.run_id }})
