name: Package

on:
  push:
  pull_request:
  repository_dispatch:
    type: [rebuild]
  workflow_dispatch:

jobs:
  build_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get build order
        id: set-build-order
        run: |
          echo "build_order=$(./get_depends.py)" >> $GITHUB_OUTPUT
          echo "container=$(echo ghcr.io/${{ github.repository_owner }}/nxdk|tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    outputs:
      build_order: ${{ steps.set-build-order.outputs.build_order }}
      container:  ${{ steps.set-build-order.outputs.container }}

  build:
    needs: [build_order]
    runs-on: ubuntu-latest
    container: ${{ needs.build_order.outputs.container }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.build_order.outputs.build_order) }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare pacman
        run: |
          cp .github/workflows/config/pacman.conf /etc/pacman.conf
          cp .github/workflows/config/makepkg.conf /etc/makepkg.conf
          mkdir -p /usr/src/nxdk/var/lib/pacman/  /usr/src/nxdk/var/cache/pacman/ /usr/src/nxdk/log /usr/src/nxdk/pacman.d/
      - name: Build package
        run: |
          eval $(/usr/src/nxdk/bin/activate -s)
          for f in ${{ matrix.package }}; do
          chown -R nobody:nobody $f
          cd $f
          sudo -u nobody NXDK_DIR=${NXDK_DIR} makepkg -p NXBUILD --cleanbuild --ignorearch --noconfirm
          pacman -U --noconfirm *.pkg.* --overwrite '*'
          cd ..
          done
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ${{ env.PACKAGE }}/*.pkg.tar.gz
